_BASE_: "Base-BALMS-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "./pretrains/sigmoid_resampling_mask_rcnn_R_50_FPN_1x.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: BalancedSoftmaxROIHeads
    NUM_CLASSES: 1230
    SCORE_THRESH_TEST: 0.0001
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("lvis_v0.5_train",)
  TEST: ("lvis_v0.5_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (11000, 18000)
  MAX_ITER: 22000

META_REWEIGHT: False